# Site settings
title: Jesper Gundlund Johansen
email: jesper@gundlund.com
description: > # this means to ignore newlines until "baseurl:"
  Dette er en beskrivelse af mig. Bla bla bla.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
permalink: posts/:title


# Social sites
twitter_username: jayjdk
github_username:  jayj

# Build settings
markdown: kramdown

sass:
    style: :expanded
